name: Sync to Databricks Git Folder

# 1. This tells GitHub to run this job only when you push to the main branch
on:
  push:
    branches:
      - main

jobs:
  update-databricks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install the official Databricks CLI tool
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      # 3. Authenticate and update the folder with the latest code
      - name: Update Databricks Git Folder
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks repos update "/Workspace/Retail_Sales_DWH/retail-sales-dwh" --branch main 